author: lamkeizyi
entity: Nb
package: com.nb
db:
  table: t_nb
  database: nb-smork
  host: 47.98.45.180
  port: 3306
  user: root
  password: 950426

templates:
  - template: controller.t
  - template: service.t
  - template: domain.t
  - template: service_impl.t
  - template: mapper.t
  - template: list_html.t
  - template: mapper_xml.t