author: lamkeizyi
entity: Label
package: com.keizyi
db:
  table: t_label
  database: records
  host: localhost
  port: 3306
  user: root
  password: 123456

templates:
  - template: controller.t
  - template: service.t